/**
 * Hardcoded watchlist of symbols to always monitor across all accessible exchanges.
 * Sourced from top 683 coins by market cap (CoinGecko/CMC snapshot).
 * Scanner will fetch prices for these even if they are not on Gate.io.
 */

export const WATCHLIST_SYMBOLS = new Set<string>([
  "A7A5","AAVE","AB","ACRED","ADA","ADI","AERO","AEUR","AGENTFUN","AIC","AIOZ","AKT","ALCH","ALEO","ALGO","ALT","AMP","ANA","ANKR","ANVL","APE","APEPE","APES","APEX","API3","APT","APXUSD","APYUSD","AR","ARB","ARC","ARDR","ARIA","ARKM","ARRR","ASBNB","ASTER","ASTR","ATH","ATOM","ATONE","ATOS","AUSD","AUSDT","AVAX","AVNT","AVUSD","AWE","AWETH","AXL",
  "AXS","AZTEC","BABY","BABYDOGE","BAN","BANANAS31","BAND","BARD","BASEDHYPE","BAT","BBSOL","BBT","BBTC","BC","BCAP","BCE","BCH","BDCA","BDX","BEAM","BEAT","BERA","BFUSD","BGB","BIM","BIRB","BLUR","BMX","BNB","BNKR","BNSOL","BONK","BORA","BORG","BOTX","BP","BRBTC","BRETT","BRLV","BRZ","BSOL","BSV","BTC","BTSE","BTT","BTW","BUIDL","BURN","BUSD",
  "CAKE","CASH","CBBTC","CBETH","CBXRP","CC","CCD","CDCETH","CELO","CET","CETH","CFG","CFX","CGUSD","CHEEMS","CHZ","CKB","CLBTC","CMETH","COAI","COINON","COLLECT","COMP","CORE","COW","CRCLON","CRCLX","CRO","CRV","CRVUSD","CSPR","CTC","CUSD","CVX","CYS",
  "DAG","DAI","DASH","DBR","DCR","DEEP","DESO","DEXE","DFDVSOL","DGB","DOG","DOGE","DOLA","DOT","DRIFT","DRV","DSOL","DUSD","DUSK","DYDX",
  "EARNAUSD","EBTC","EDU","EETH","EGL1","EGLD","EIGEN","ELF","ELG","ELON","ENA","ENJ","ENS","ENZOBTC","ESP","ESPORTS","ETC","ETH","ETHFI","ETHX","EURC","EURCV","EURI","EURS","EUTBL","EXOD","EZETH",
  "FAI","FARTCOIN","FB","FBTC","FDIT","FDUSD","FET","FEUSD","FF","FIDD","FIGR_HELOC","FIL","FIUSD","FLOKI","FLOW","FLR","FLUID","FO","FOGO","FORM","FRAX","FRXETH","FRXUSD","FT","FTN","FUL","FWSTETH","FXRP",
  "GAL","GALA","GAS","GEKKO","GEOD","GHO","GLIDR","GLM","GMRT","GMX","GNO","GOHOME","GOMINING","GRASS","GRT","GRX","GT","GTBTC","GTETH","GTUSDC","GUN","GUSD","GWEI",
  "HASH","HASUI","HBAR","HBTC","HEZ","HNT","HOME","HOT","HSK","HSOL","HTX","HYPE",
  "IBERA","ICNT","ICP","ICX","IDOL","IMX","INI","INJ","IOST","IOTA","IOTX","IP","IRYS","ISLM","IUSD",
  "JAAA","JASMY","JCT","JELLYJELLY","JITOSOL","JLP","JSOL","JST","JTO","JTRSY","JUP","JUPSOL","JUPUSD","JUSD",
  "KAIA","KAITO","KAS","KAU","KAVA","KBTC","KCS","KGEN","KHYPE","KITE","KMNO","KOGE","KSM","KTA","KUB",
  "LA","LB","LBT","LBTC","LCX","LDO","LEO","LINK","LION","LIQUIDETH","LISUSD","LIT","LON","LPT","LSETH","LTC","LUNA","LUNC","LUX",
  "MANA","MANTRA","MASK","MBG","MBTC","ME","MELANIA","MEME","MET","META","METAL","METH","MEW","MGG","MHYPER","MHYPERBTC","MIM","MINA","MNEE","MNGO","MNT","MOCA","MOG","MON","MOODENG","MORPHO","MOVE","MSOL","MSUSD","MSY","MTBILL","MVL","MWC","MWETH","MWUSDC","MX","MYX",
  "NEAR","NEO","NEXO","NFT","NIGHT","NILA","NIZA","NMR","NOT","NOW","NPC","NUSD","NXM","NXPC",
  "OETH","OFT","OHM","OKB","OM","OMNI","ONDO","ONT","ONYC","OP","OPEN","OPN","ORBS","ORCA","ORDI","OSETH","OUSG","OZO",
  "PAXG","PENDLE","PENGU","PEPE","PGOLD","PI","PIEVERSE","PIPPIN","PLLD","PLUME","PM","PMUSD","PNUT","POL","POLYX","POPCAT","PRIME","PROVE","PSOL","PSTUSDC","PTGC","PUFF","PUMP","PUMPBTC","PUNDIX","PURR","PUSD","PYTH","PYTHIA","PYUSD","PZETH",
  "QAI","QNT","QRL","QTUM","QUAI","QUBIC","QUSDT",
  "RAIL","RAIN","RAVE","RAY","REAL","RED","REKT","RENDER","REQ","RETH","REUSD","RIF","RIVER","RLB","RLUSD","ROBO","RON","ROSE","RPL","RSETH","RSR","RSWETH","RUNE","RVN",
  "SAFE","SAHARA","SAND","SATUSD","SAVAX","SAVUSD","SB","SBTC","SC","SCRVUSD","SDAI","SEI","SENA","SENT","SFP","SFRXETH","SHFL","SHIB","SIERRA","SIGN","SIREN","SKL","SKR","SKY","SKYAI","SNT","SNX","SOETH","SOL","SOLVBTC","SOON","SOS","SOSO","SPK","SPX","SQD","SRUSDE","STABLE","STEAKETH","STEAKUSDC","STETH","STG","STHYPE","STKAAVE","STRK","STRX","STUSDT","STX","STXRP","SUI","SUN","SUPER","SUPEROETH","SUSDAI","SUSDD","SUSDE","SUSDS","SUSHI","SWETH","SWOP","SXT","SYRUP","SYRUPUSDC","SYRUPUSDT","SYZUSD",
  "TAG","TAO","TBK","TBTC","TDCCP","TEL","TEMPLE","TETH","TFUEL","THBILL","THETA","TIA","TIBBIR","TKX","TON","TOSHI","TRAC","TRB","TRIA","TRUMP","TRX","TSLAX","TURBO","TUSD","TWT",
  "UAI","UB","UBTC","UDS","ULTIMA","UMA","UNI","UNIBTC","UNP","UNT","UPUMP","USD0","USD1","USDA","USDAI","USDC","USDD","USDE","USDF","USDG","USDGO","USDKG","USDM","USDO","USDON","USDP","USDR","USDS","USDT","USDT0","USDTB","USDU","USDX","USDY","USELESS","USR","USTB","USTBL","USX","USYC","UUSD",
  "VANA","VBETH","VBILL","VBUSDC","VBUSDT","VBWBTC","VCNT","VELO","VENOM","VET","VIRTUAL","VKHYPE","VR","VRSC","VSN","VSOL","VTHO","VVS","VVV",
  "WAETHUSDC","WAETHUSDT","WAETHWETH","WAL","WAPE","WAVAX","WAVES","WBETH","WBNB","WBT","WBTC","WCRO","WDAG","WEETH","WEETHS","WEMIX","WETH","WFI","WFLR","WFOGO","WHYPE","WIF","WKC","WLD","WLFI","WM","WMTX","WOJ","WOULD","WPLS","WRSETH","WSTETH","WSTX","WTRX","WYLDS",
  "XAUM","XAUT","XAUT0","XBTC","XCH","XCN","XDAI","XDC","XEC","XLM","XMR","XNO","XPL","XPR","XRP","XSOLVBTC","XTZ","XUSD","XVG","XVS","XYO",
  "YFI","YLDS","YUSD","YZUSD","YZY",
  "ZAMA","ZANO","ZBCN","ZCHF","ZEC","ZEN","ZETA","ZIG","ZIL","ZK","ZORA","ZRO","ZRX",
]);

export const WATCHLIST_ARRAY = [...WATCHLIST_SYMBOLS];
